# Generated by Django 6.0 on 2025-12-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ano_publicacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
