# Generated by Django 6.0 on 2025-12-19 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_livro_ano_publicacao_remove_livro_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='data_devolucao',
            field=models.DateField(default=datetime.date(2025, 12, 19)),
            preserve_default=False,
        ),
    ]
