# Generated by Django 6.0 on 2025-12-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_locacao_data_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='area',
            field=models.CharField(default='Geral', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='Desconhecido', max_length=150),
            preserve_default=False,
        ),
    ]
